name: list_smith_example
description: "Runnable example app for the list_smith package."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  list_smith:
    path: ../

  pmvvm: ^4.0.1
  platform_adaptive_widgets: ^2.1.0
  material_ui: ^0.0.1
  cupertino_ui: ^0.0.1
  platform_icons: ^0.1.1
  listenable_collections: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  checks: ^0.3.1

flutter:
  uses-material-design: true
